// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-expenses.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/with-logging.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
async function logMcpCall(ctx, toolName, status, errorMessage, durationMs) {
  try {
    if (!ctx.isAuthenticated()) return;
    const sb = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    await sb.from("mcp_tool_logs").insert({
      user_id: ctx.getUserId(),
      tool_name: toolName,
      status,
      error_message: errorMessage,
      duration_ms: durationMs
    });
  } catch {
  }
}
function withLogging(toolName, handler) {
  return async (input, ctx) => {
    const start = Date.now();
    try {
      const result = await handler(input, ctx);
      const isError = !!(result && result.isError);
      const errMsg = isError ? result?.content?.[0]?.text ?? "unknown error" : null;
      await logMcpCall(
        ctx,
        toolName,
        isError ? "error" : "success",
        errMsg,
        Date.now() - start
      );
      return result;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      await logMcpCall(ctx, toolName, "error", msg, Date.now() - start);
      throw err;
    }
  };
}

// src/lib/mcp/tools/list-expenses.ts
function supabaseForUser(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_expenses_default = defineTool({
  name: "list_expenses",
  title: "Popis tro\u0161kova",
  description: "Vra\u0107a tro\u0161kove prijavljenog korisnika. Podr\u017Eava filtriranje po datumskom rasponu (from/to, ISO datum YYYY-MM-DD) i ograni\u010Denje broja rezultata.",
  inputSchema: {
    from: z.string().optional().describe("Po\u010Detni datum (YYYY-MM-DD), uklju\u010Divo."),
    to: z.string().optional().describe("Krajnji datum (YYYY-MM-DD), uklju\u010Divo."),
    limit: z.number().int().positive().max(500).optional().describe("Maksimalan broj tro\u0161kova (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withLogging("list_expenses", async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niste prijavljeni." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("expenses").select("id, amount, description, expense_date, category_id, expense_categories(name)").order("expense_date", { ascending: false }).limit(limit ?? 100);
    if (from) query = query.gte("expense_date", from);
    if (to) query = query.lte("expense_date", to);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      amount: r.amount,
      description: r.description,
      expense_date: r.expense_date,
      category: r.expense_categories?.name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { expenses: rows, count: rows.length }
    };
  })
});

// src/lib/mcp/tools/create-expense.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_expense_default = defineTool2({
  name: "create_expense",
  title: "Dodaj tro\u0161ak",
  description: "Dodaje novi tro\u0161ak za prijaljenog korisnika. Kategorija se pronalazi po imenu (ako je navedena).",
  inputSchema: {
    amount: z2.number().positive().describe("Iznos tro\u0161ka u eurima."),
    description: z2.string().min(1).describe("Kratak opis tro\u0161ka."),
    expense_date: z2.string().optional().describe("Datum tro\u0161ka (YYYY-MM-DD). Default: danas."),
    category: z2.string().optional().describe("Naziv kategorije (npr. 'Hrana'). Opcionalno.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: withLogging("create_expense", async ({ amount, description, expense_date, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niste prijavljeni." }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let categoryId = null;
    if (category) {
      const { data: cats } = await sb.from("expense_categories").select("id, name").ilike("name", category).limit(1);
      categoryId = cats?.[0]?.id ?? null;
    }
    const { data, error } = await sb.from("expenses").insert({
      user_id: ctx.getUserId(),
      amount,
      description,
      expense_date: expense_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      category_id: categoryId
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Tro\u0161ak spremljen: ${data.description} (${data.amount} \u20AC).` }],
      structuredContent: { expense: data }
    };
  })
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser3(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Popis kategorija",
  description: "Vra\u0107a sve kategorije tro\u0161kova dostupne prijavljenom korisniku (zadane i vlastite).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withLogging("list_categories", async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niste prijavljeni." }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("expense_categories").select("id, name, icon, color").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { categories: data ?? [] }
    };
  })
});

// src/lib/mcp/tools/expense-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var expense_summary_default = defineTool4({
  name: "expense_summary",
  title: "Sa\u017Eetak tro\u0161kova",
  description: "Vra\u0107a ukupan iznos i razradu po kategorijama za zadani datumski raspon (default: teku\u0107i mjesec).",
  inputSchema: {
    from: z3.string().optional().describe("Po\u010Detni datum (YYYY-MM-DD)."),
    to: z3.string().optional().describe("Krajnji datum (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: withLogging("expense_summary", async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niste prijavljeni." }], isError: true };
    }
    const now = /* @__PURE__ */ new Date();
    const defaultFrom = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10);
    const defaultTo = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10);
    const rangeFrom = from ?? defaultFrom;
    const rangeTo = to ?? defaultTo;
    const { data, error } = await supabaseForUser4(ctx).from("expenses").select("amount, expense_categories(name)").gte("expense_date", rangeFrom).lte("expense_date", rangeTo);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byCategory = {};
    let total = 0;
    for (const row of data ?? []) {
      const name = row.expense_categories?.name ?? "Ostalo";
      const amt = Number(row.amount) || 0;
      byCategory[name] = (byCategory[name] ?? 0) + amt;
      total += amt;
    }
    const summary = {
      from: rangeFrom,
      to: rangeTo,
      total: Math.round(total * 100) / 100,
      by_category: Object.entries(byCategory).map(([name, amount]) => ({ name, amount: Math.round(amount * 100) / 100 })).sort((a, b) => b.amount - a.amount)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  })
});

// src/lib/mcp/index.ts
var projectRef = "xrizhnaixeyykogwallr";
var mcp_default = defineMcp({
  name: "kucni-budzet-mcp",
  title: "Ku\u0107ni bud\u017Eet MCP",
  version: "0.1.0",
  instructions: "Alati za aplikaciju Ku\u0107ni bud\u017Eet. Koristi list_expenses za pregled tro\u0161kova, expense_summary za sa\u017Eetak po kategorijama, list_categories za popis kategorija i create_expense za dodavanje novog tro\u0161ka.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_expenses_default, expense_summary_default, list_categories_default, create_expense_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
